# Generated by Django 4.2.5 on 2024-08-16 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumInfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=100)),
                ('totalTracks', models.IntegerField()),
                ('releaseDate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistInfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('currentSongTerm', models.CharField(max_length=100)),
                ('currentArtistTerm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrackInfo',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('songName', models.CharField(max_length=100)),
                ('artistName', models.CharField(max_length=100)),
                ('albumName', models.CharField(max_length=100)),
                ('coverUrls', models.JSONField(blank=True, null=True)),
                ('previewUrl', models.CharField(blank=True, max_length=100, null=True)),
                ('albumId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='api.albuminfo')),
                ('artistId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='api.artistinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TrackRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('term', models.CharField(max_length=100)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.musicreport')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trackinfo')),
            ],
        ),
        migrations.AddField(
            model_name='musicreport',
            name='design',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.reportdesign'),
        ),
        migrations.AddField(
            model_name='musicreport',
            name='longTermArtists',
            field=models.ManyToManyField(blank=True, related_name='lArtists', to='api.artistinfo'),
        ),
        migrations.AddField(
            model_name='musicreport',
            name='longTermSongs',
            field=models.ManyToManyField(blank=True, related_name='lSongs', to='api.trackinfo'),
        ),
        migrations.AddField(
            model_name='musicreport',
            name='mediumTermArtists',
            field=models.ManyToManyField(blank=True, related_name='mArtists', to='api.artistinfo'),
        ),
        migrations.AddField(
            model_name='musicreport',
            name='mediumTermSongs',
            field=models.ManyToManyField(blank=True, related_name='mSongs', to='api.trackinfo'),
        ),
        migrations.AddField(
            model_name='musicreport',
            name='shortTermArtists',
            field=models.ManyToManyField(blank=True, related_name='sArtists', to='api.artistinfo'),
        ),
        migrations.AddField(
            model_name='musicreport',
            name='shortTermSongs',
            field=models.ManyToManyField(blank=True, related_name='sSongs', to='api.trackinfo'),
        ),
        migrations.CreateModel(
            name='ArtistRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('term', models.CharField(max_length=100)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artistinfo')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.musicreport')),
            ],
        ),
        migrations.AddField(
            model_name='albuminfo',
            name='artistId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='api.artistinfo'),
        ),
    ]
