# Generated by Django 4.2.5 on 2024-08-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdesign',
            name='name',
            field=models.CharField(default='namefd', max_length=100),
            preserve_default=False,
        ),
    ]
