# Generated by Django 4.2.5 on 2024-08-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reportdesign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicreport',
            name='design',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reportdesign'),
        ),
    ]
