# Generated by Django 4.2.5 on 2024-08-18 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_musicreport_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicreport',
            name='_is_signal_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musicreport',
            name='design',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reportdesign'),
        ),
    ]
