# Generated by Django 4.2.5 on 2024-08-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_musicreport__is_signal_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicreport',
            name='_is_signal_processed',
        ),
    ]
