# Generated by Django 4.2.5 on 2024-08-19 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_musicreport__is_signal_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('displayName', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='reportdesign',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musicreport',
            name='design',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.reportdesign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicreport',
            name='belongsTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.userinfo'),
        ),
    ]
