# Generated by Django 4.2.5 on 2024-08-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userinfo_reportdesign_image_alter_musicreport_design_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicreport',
            name='design',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reportdesign'),
        ),
    ]
