# Generated by Django 4.2.5 on 2024-08-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_musicreport_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdesign',
            name='imagetext',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
