# Generated by Django 4.2.5 on 2024-08-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reportdesign_imagetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
