# Generated by Django 4.2.5 on 2024-08-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userinfo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='created_at',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dateCreated',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
