# Generated by Django 4.2.5 on 2024-08-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_userinfo_created_at_userinfo_datecreated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='dateCreated',
        ),
        migrations.AddField(
            model_name='musicreport',
            name='dateCreated',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
