# Generated by Django 4.2.5 on 2024-08-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_userinfo_datecreated_musicreport_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicreport',
            name='design',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.reportdesign'),
        ),
    ]
