# Generated by Django 4.2.5 on 2024-08-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_musicreport_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicreport',
            name='demo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='demo',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
