# Generated by Django 4.2.5 on 2024-08-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_musicreport_demo_userinfo_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicreport',
            name='demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='demo',
            field=models.BooleanField(null=True),
        ),
    ]
