# Generated by Django 4.2.5 on 2024-08-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_musicreport_demo_alter_userinfo_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicreport',
            name='demo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='demo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
